-- =======================================================
-- Synchronization script for table: [Production].[Document]
-- =======================================================
Print 'Synchronization script for table: [Production].[Document]'

INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/', N'Documents', 217, 1, N'Documents', N'', N'0    ', 0, 2, '20171213 13:58:03.943')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/1/', N'Overview', 217, 1, N'Overview', N'', N'0    ', 0, 2, '20171213 13:58:03.977')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/1/1/', N'Introduction 1', 219, 0, N'Introduction 1.doc', N'.doc', N'4    ', 28, 2, '20130530 00:00:00.000')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/1/2/', N'Repair and Service Guidelines', 220, 0, N'Repair and Service Guidelines.doc', N'.doc', N'0    ', 8, 2, '20080331 00:00:00.000')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/2/', N'Maintenance', 217, 1, N'Maintenance', N'', N'0    ', 0, 2, '20171213 13:58:04.007')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/2/1/', N'Crank Arm and Tire Maintenance', 219, 0, N'Crank Arm and Tire Maintenance.doc', N'.doc', N'0    ', 0, 1, '20121019 09:56:38.273')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/2/2/', N'Lubrication Maintenance', 219, 0, N'Lubrication Maintenance.doc', N'.doc', N'2    ', 11, 1, '20130530 00:00:00.000')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/3/', N'Assembly', 217, 1, N'Assembly', N'', N'0    ', 0, 2, '20171213 13:58:04.037')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/3/1/', N'Front Reflector Bracket and Reflector Assembly 3', 220, 0, N'Front Reflector Bracket and Reflector Assembly 3.doc', N'.doc', N'3    ', 25, 2, '20120430 00:00:00.000')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/3/2/', N'Front Reflector Bracket Installation', 220, 0, N'Front Reflector Bracket Installation.doc', N'.doc', N'1    ', 15, 2, '20120430 00:00:00.000')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/3/3/', N'Installing Replacement Pedals', 220, 0, N'Installing Replacement Pedals.doc', N'.doc', N'0    ', 32, 2, '20120430 00:00:00.000')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/3/4/', N'Seat Assembly', 219, 0, N'Seat Assembly.doc', N'.doc', N'8    ', 55, 2, '20130430 00:00:00.000')
INSERT INTO [Production].[Document] ([DocumentNode], [Title], [Owner], [FolderFlag], [FileName], [FileExtension], [Revision], [ChangeNumber], [Status], [ModifiedDate]) VALUES ('/3/5/', N'Training Wheels 2', 220, 0, N'Training Wheels 2.doc', N'.doc', N'1    ', 288, 3, '20130530 00:00:00.000')
